const defiLaunchPadSlice = (set) => ({
  softCap: "",
  hardCap: "",
  minimumBuy: "",
  maximumBuy: "",
  refundType: "0",
  router: "PancakeSwap",
  liquidity: "",
  listingRate: "",
  startDate: "",
  endDate: "",
  tokenAddress: "",
  preSale: "",
  isWhiteListed: "0",
  tokensStatus: "0",
  setTokenStatus: (input) => set((state) => ({ tokensStatus: input })),
  setIsWhiteListed: (input) => set((state) => ({ isWhiteListed: input })),
  setPreSale: (input) => set((state) => ({ preSale: input })),
  setTokenAddress: (input) => set((state) => ({ tokenAddress: input })),
  setSoftCap: (input) => set((state) => ({ softCap: input })),
  setHardCap: (input) => set((state) => ({ hardCap: input })),
  setMinimumBuy: (input) => set((state) => ({ minimumBuy: input })),
  setmaximumBuy: (input) => set((state) => ({ maximumBuy: input })),
  setrefundType: (input) => set((state) => ({ refundType: input })),
  setRouter: () => set((state) => ({ Router: "PancakeSwap" })),
  setLiquidity: (input) => set((state) => ({ liquidity: input })),
  setListingRate: (input) => set((state) => ({ listingRate: input })),
  setStartDate: (input) => set((state) => ({ startDate: input })),
  setEndDate: (input) => set((state) => ({ endDate: input })),
});

export default defiLaunchPadSlice;
